version: '3'

services:
  mailtrap:
    image: maildev/maildev:latest
    container_name: mailtrap
    ports:
      - "1080:1080"   # Web interface (Mailtrap UI)
      - "1025:1025"   # SMTP port
    environment:
      - MAILDEV_INCOMING_USER=mailtrap
      - MAILDEV_INCOMING_PASS=mailtrap

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    restart: unless-stopped
    environment:
      MEMCACHED_MEMORY: 64
      MEMCACHED_MAX_CONNECTIONS: 1024

volumes:
  redis_data:
