CREATE TABLE sessions (
    id INT AUTO_INCREMENT PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    message VARCHAR(255) NOT NULL
)