CREATE TABLE jobs (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NULL,
    is_visible BOOLEAN NOT NULL DEFAULT TRUE,
    message BYTEA
)