CREATE TABLE jobs (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    name VARCHAR(255) NOT NULL,
    topic VARCHAR(255) NULL,
    is_visible TINYINT(1) NOT NULL DEFAULT 1,
    message VARCHAR(255) NOT NULL
)