version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: migrator
      MYSQL_USER: migrator
      MYSQL_PASSWORD: H8E7kU8Y
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  firebird:
    image: jacobalberty/firebird:latest
    container_name: firebird_container
    environment:
      ISC_PASSWORD: masterkey
    ports:
      - "3050:3050"
    volumes:
      - ./firebird_data/init_db.sh:/docker-entrypoint-initdb.d/init_db.sh:ro
      - firebird_data:/firebird

  mailtrap:
    image: maildev/maildev:latest
    container_name: mailtrap
    ports:
      - "1080:1080"   # Web interface (Mailtrap UI)
      - "1025:1025"   # SMTP port
    environment:
      - MAILDEV_INCOMING_USER=mailtrap
      - MAILDEV_INCOMING_PASS=mailtrap

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"
    environment:
      MEMCACHED_MEMORY: 64
      MEMCACHED_MAX_CONNECTIONS: 1024

volumes:
  redis_data:
  mysql_data:
  postgres_data:
  firebird_data:
  